### ISSUE TITLE
"require" only works with absolute paths

### ISSUE THREAD

**Issue by NicoleRauch** [noamtcohen/SlimJS#4]
I've created a fixture which works fine. But when I try to pull in production code, this does not work when using a relative path:

Fixture "Fixture.js":
```
// does not work:
var x = require("./prodCode");

function Fixture () {
    this.output = function () {
        return x.X;
    }
}
``` 

Production code "prodCode.js" in the same directory:
```
module.exports = {
    X : "X"
};
```

If I use the full path in require(), it works fine, though.

Can you please tell me how I can access production code from a fixture while using relative paths?

**Comment by noamtcohen** [comment]
Hi @NicoleRauch, I know this is not exactly correct but try `require("prodCode.js");` (without the dot-slash)

**Comment by NicoleRauch** [comment]
Hm... and how would that work with "real" production code? I'd rather prefer not to have the fixtures in the same directories to be honest...

**Comment by noamtcohen** [comment]
It's a good point but I don't control the [VM](https://nodejs.org/api/vm.html) require function, I did struggle with this: [Sandbox.js#L50](https://github.com/noamtcohen/SlimJS/blob/master/src/Sandbox.js#L50)
But I found that this problem only happens when you are trying to require code that **is** in the same directory. Really your fixture code doesn't have to know the path to the productions code. all you have to do to make the production code available for the fixture is by adding the import in FitNesses.
In a project I'm working on this is my directory tree:
```
root
   server
       prod.js
   test
       test-script
           some-test.js
       FitNesses.jar
```
This is what my FitNesse root setup looks like
```
!define TEST_SYSTEM {slim}
!define COMMAND_PATTERN {node node_modules/slimjs/src/SlimJS %p}
!path test-scripts
!path ../
```
So in `some-test.js` I do things like `require('server/prod.js')`

As I write these lines I don't think I needed, in my case, production code to load additional production scripts it the same directory of the production code I was testing so this has to be checked, maybe you can try and let me know. if you have a suggestion for a solution I think a good place to implement it would be in the [sandbox](https://github.com/noamtcohen/SlimJS/blob/master/src/Sandbox.js).
(I think in the worst case we could just parse the js file before loading it into the VM and replacing the require statements with an absolute path. not elegant but would do the job.)

**Comment by noamtcohen** [comment]
This is an important bug. The problem was that when I was loading the fixture code I was doing it by reading the file with `fs` and then executing it in the VM so require lost it's meaning by not knowing the script path. I've committed an update but haven't pushed to NPM yet. Pull this commit and add to the bottom of the fixture code `module.exports.Fixture=Fixture`. You can see the examples in the updated readme.

**Comment by noamtcohen** [comment]
I've published the change to NPM. The require statements should work as they should.
Could you please test this too?

**Comment by NicoleRauch** [comment]
Thank you! I will try it out today or tomorrow and get back to you.

**Comment by NicoleRauch** [comment]
This works now, thank you!
